version: '2'

services:
  wifi-repeater:
    image: bh.cr/gh_scott_hamilton/wifi-repeater-block
    privileged: true
    network_mode: host

  balena-fox-backup:
    image: bh.cr/gh_scott_hamilton/balena-fox-backup


